version: "3.7"

services:
    web:
        container_name: credit-score-bank-frontend
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ".:/frontend"
            - "/frontend/node_modules"
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
